version: "3.8"

services:
  app:
    image: wns0901/talktodo-server:latest
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUD_AWS_S3_BUCKET=${CLOUD_AWS_S3_BUCKET}
      - CLOUD_AWS_REGION_STATIC=${CLOUD_AWS_REGION_STATIC}
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      - API_URL=${API_URL}
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: unless-stopped
